"""add langfuse keys

Revision ID: 1fe22694f10b
Revises: 259009aab396
Create Date: 2026-04-18 19:18:19.289330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fe22694f10b"
down_revision: Union[str, Sequence[str], None] = "259009aab396"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("langfuse_public_key", sa.String(), nullable=True))
    op.add_column("User", sa.Column("langfuse_secret_key", sa.String(), nullable=True))
    op.alter_column("User", "password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("User", "password", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("User", "langfuse_secret_key")
    op.drop_column("User", "langfuse_public_key")
    # ### end Alembic commands ###
