"""make_password_nullable

Revision ID: 259009aab396
Revises: 28125649e364
Create Date: 2026-02-25 21:43:16.132781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "259009aab396"
down_revision: Union[str, Sequence[str], None] = "28125649e364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("User", "password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("User", "password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
