"""Add FineTuneRequest and finetuner_expires_at

Revision ID: a1cb6bdba93c
Revises: 1fe22694f10b
Create Date: 2026-04-23 23:42:26.033903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cb6bdba93c'
down_revision: Union[str, Sequence[str], None] = '1fe22694f10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FineTuneRequest',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('necessity', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='FineTuneRequestStatus'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('User', sa.Column('finetuner_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'finetuner_expires_at')
    op.drop_table('FineTuneRequest')
    # ### end Alembic commands ###
