"""init_db

Revision ID: d6ff8424b62c
Revises:
Create Date: 2026-02-02 21:06:23.111820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d6ff8424b62c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_index("ix_User_identifier", "User", ["identifier"], unique=False)
    op.create_table(
        "Thread",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deletedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("ARRAY[]::text[]"),
            nullable=False,
        ),
        sa.Column("userId", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_Thread_createdAt", "Thread", ["createdAt"], unique=False)
    op.create_index("ix_Thread_name", "Thread", ["name"], unique=False)
    op.create_table(
        "Step",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("parentId", sa.UUID(), nullable=True),
        sa.Column("threadId", sa.UUID(), nullable=True),
        sa.Column("input", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("output", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "assistant_message",
                "embedding",
                "llm",
                "retrieval",
                "rerank",
                "run",
                "system_message",
                "tool",
                "undefined",
                "user_message",
                name="StepType",
            ),
            nullable=False,
        ),
        sa.Column("showInput", sa.String(), server_default="json", nullable=True),
        sa.Column("isError", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("startTime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("endTime", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["parentId"], ["Step.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["threadId"], ["Thread.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_Step_createdAt", "Step", ["createdAt"], unique=False)
    op.create_index("ix_Step_endTime", "Step", ["endTime"], unique=False)
    op.create_index("ix_Step_name", "Step", ["name"], unique=False)
    op.create_index("ix_Step_parentId", "Step", ["parentId"], unique=False)
    op.create_index("ix_Step_startTime", "Step", ["startTime"], unique=False)
    op.create_index("ix_Step_threadId", "Step", ["threadId"], unique=False)
    op.create_index(
        "ix_Step_threadId_startTime_endTime",
        "Step",
        ["threadId", "startTime", "endTime"],
        unique=False,
    )
    op.create_index("ix_Step_type", "Step", ["type"], unique=False)
    op.create_table(
        "Element",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("threadId", sa.UUID(), nullable=True),
        sa.Column("stepId", sa.UUID(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mime", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("objectKey", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("chainlitKey", sa.String(), nullable=True),
        sa.Column("display", sa.String(), nullable=True),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["stepId"], ["Step.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["threadId"], ["Thread.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_Element_stepId", "Element", ["stepId"], unique=False)
    op.create_index("ix_Element_threadId", "Element", ["threadId"], unique=False)
    op.create_table(
        "Feedback",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("stepId", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stepId"],
            ["Step.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_Feedback_createdAt", "Feedback", ["createdAt"], unique=False)
    op.create_index("ix_Feedback_name", "Feedback", ["name"], unique=False)
    op.create_index(
        "ix_Feedback_name_value", "Feedback", ["name", "value"], unique=False
    )
    op.create_index("ix_Feedback_stepId", "Feedback", ["stepId"], unique=False)
    op.create_index("ix_Feedback_value", "Feedback", ["value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_Feedback_value", table_name="Feedback")
    op.drop_index("ix_Feedback_stepId", table_name="Feedback")
    op.drop_index("ix_Feedback_name_value", table_name="Feedback")
    op.drop_index("ix_Feedback_name", table_name="Feedback")
    op.drop_index("ix_Feedback_createdAt", table_name="Feedback")
    op.drop_table("Feedback")
    op.drop_index("ix_Element_threadId", table_name="Element")
    op.drop_index("ix_Element_stepId", table_name="Element")
    op.drop_table("Element")
    op.drop_index("ix_Step_type", table_name="Step")
    op.drop_index("ix_Step_threadId_startTime_endTime", table_name="Step")
    op.drop_index("ix_Step_threadId", table_name="Step")
    op.drop_index("ix_Step_startTime", table_name="Step")
    op.drop_index("ix_Step_parentId", table_name="Step")
    op.drop_index("ix_Step_name", table_name="Step")
    op.drop_index("ix_Step_endTime", table_name="Step")
    op.drop_index("ix_Step_createdAt", table_name="Step")
    op.drop_table("Step")
    op.drop_index("ix_Thread_name", table_name="Thread")
    op.drop_index("ix_Thread_createdAt", table_name="Thread")
    op.drop_table("Thread")
    op.drop_index("ix_User_identifier", table_name="User")
    op.drop_table("User")
    # ### end Alembic commands ###
