"""add firstname, lastname, email to User entity

Revision ID: 28125649e364
Revises: 71edb0951243
Create Date: 2026-02-06 20:57:28.408379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28125649e364'
down_revision: Union[str, Sequence[str], None] = '71edb0951243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email')
    op.drop_column('User', 'lastname')
    op.drop_column('User', 'firstname')
    # ### end Alembic commands ###
