"""add_user_roles_pswrd

Revision ID: 71edb0951243
Revises: d6ff8424b62c
Create Date: 2026-02-06 20:19:55.689997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71edb0951243'
down_revision: Union[str, Sequence[str], None] = 'd6ff8424b62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_name = 'UserRole'
enum_values = ('admin', 'fine_tuner', 'normal', 'unauthorized')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust!
    user_role_enum = sa.Enum(*enum_values, name=enum_name)
    user_role_enum.create(op.get_bind())
    op.add_column('User', sa.Column('password', sa.String(), nullable=False))
    op.add_column('User', sa.Column('role', user_role_enum, nullable=False))
    op.create_index('ix_User_role', 'User', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_role', table_name='User')
    op.drop_column('User', 'role')
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
